#!/bin/bash

if [ $# -ne 2 ] # dollar hash is the number of command line arguments
  then
    echo "Usage: $0 commandToTest testSetFile" >&2 # stderr
    exit 1 # non-zero exit code to signal unintended behaviour
  fi

cmd=$1
test_set_file=$2

myTemp=$(mktemp)
for arg in $(cat ${test_set_file}); do
  $cmd < "${arg}.in" > ${myTemp}
  if diff "${arg}.out" "${myTemp}" > /dev/null;
    then
      echo "Test ${arg} passed"
    else
      echo "Test ${arg} failed"
      echo "Expected output:"
      cat "${arg}.out"
      echo "Actual output:"
      cat "${myTemp}"
    fi
rm $myTemp
done
