#!/bin/bash
if [ $# -ne 1 ] # dollar hash is the number of command line arguments
  then
    echo "Usage: $0 testSetFile" >&2 # stderr
    exit 1 # non-zero exit code to signal unintended behaviour
  fi

if [[ ! -f $1 ]]; then # -f checks if the first arguement refers to an existing directory
  exit 1
fi

for arg in $(cat $1); do
  if [ -e "${arg}.desc" ]; # -e means exists
    then
      cat "${arg}.desc"
    else
      echo "${arg} No test description"
  fi
done