#!/bin/bash
if [ $# -ne 1 ] # dollar hash is the number of command line arguments
  then
    echo "Usage: $0 <filename>" >&2 # stderr
    exit 1 # non-zero exit code to signal unintended behaviour
  fi

for arg in $(cat $1); do
  if [ -e "${arg}.desc" ]; # -e means exists
    then
      cat "${arg}.desc"
    else
      echo "${arg}: No test description"
  fi
done